print('\nMEDIDAS DE POSIÇÃO:')
    # print(30*'-')
    # print('Mínimo: ', minimo)
    # print(f'Limite Inferior: {limite_inferior:.2f}')
    # print('Q1 (25%): ', q1)
    # print('Q2 (50%): ', q2)
    # print('Q3 (75%): ', q3)
    # print(f'IQR: {iqr:.2f}')
    # print(f'Limite Superior: {limite_superior:.2f}')
    # print('Máximo: ', maximo)